### ISSUE TITLE
Error Message on ./openvpn_clients.sh

### ISSUE THREAD

**Issue by marvinstuart** [meveric/odroid-server#1] opened 2015-02-21 15:44 UTC
./openvpn_clients.sh: line 52: msgbox: command not found
cp: cannot stat '/etc/openvpn/jamaica/keys/testing.crt': No such file or directory
root@odroid-server:~/odroid-server#

In the keys folder  i see Nameclient.ovpn and Nameclient.key and ca.crt  but not the Nameclient.crt
 @meveric email me email me at marvin g stuart AT gmail com

**Comment by meveric** [comment] 2015-02-21 16:18
did you try running the script manually?

"msgbox: command not found" only should show if you try to start the script itself..
Normally all tasks are done over odroid-server.sh
You do not start the different parts individually.

If that doesn't help i can look into it again.. I haven't worked on the OpenVPN for a while.. i think it's still missing a few options..

**Comment by marvinstuart** [comment] 2015-02-21 16:55
i did  run the script via terminal 

steps 
via terminal
1:  git clone https://github.com/meveric/odroid-server.git
2: cd odroid-server
3:  chmod +x openvpn_clients.sh 
4: chmod +x openvpn_clients.sh 
5: ./openvpn_server.sh (seems to work fine)
6: /openvpn_clients.sh

after #6 it should create and moved to keys to a keys folder - (below are the keys) 
ca.crt                  # Server CA file ( IN THE KEYS FOLDER )
crt      # client certificate (NOT IN THE KEYS FOLDER )
key      # private key file (should kept secret) (IN THE KEYS FOLDER )
ovpn     # OpenVPN configuration file for OpenVPN clients (IN THE KEYS FOLDER )

Its seems it not create the   client certificate file

Error message
openvpn_clients.sh: line 52: msgbox: command not found
cp: cannot stat '/etc/openvpn/jamaica/keys/newtest.crt': No such file or directory

a link to the setups 
https://www.digitalocean.com/community/tutorials/how-to-setup-and-configure-an-openvpn-server-on-centos-6

**Comment by meveric** [comment] 2015-02-21 17:07
ok, as i said it's the wrong steps to start openvpn_server and openvpn_client
there is a reason why only odroid-server.sh is executable and the others are not.

Please start odroid-server.sh and use the step from there and see if it works..
The individual parts are not meant to start manually..

**Comment by marvinstuart** [comment] 2015-02-21 17:27
Ok use 

odroid-server.sh

still getting error message  
cp: cannot stat '/etc/openvpn/easy-rsa/keys/jamaica.crt': No such file or directory

I can give you ssh access if you need just email me

**Comment by meveric** [comment] 2015-02-21 17:32
ok, let me try on a clean image i'll check where this happens..

**Comment by meveric** [comment] 2015-02-21 17:48
I just tried and it went through without an issue...
can you delete everything you have in /etc/openvpn (besides the update-resolve.conf) and try over again?
If it doesn't work i can try over SSH

**Comment by marvinstuart** [comment] 2015-02-21 18:02
It goes though fine but if you look into the terminal you see the error 

didnt work sorry  email is marvingstuart@gmail.com

**Comment by meveric** [comment] 2015-02-21 19:29
Issue resulted from not using the odroid-server.sh script but directly starting the openvpn-server.sh script..

I'll have to add some information on how to use this, and probably add some checks to prevent starting the scripts directly.

Still, not a bug, so i'm gonna close this.

**Closed as completed by meveric** 2015-02-21 19:29 UTC
Labels: invalid
